HTTP 500 triggers warning instead of error
  line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 500 Server Error: Internal Server Error

  File "./vms.py", line 635, in get_json
    raise ApiHttpException(exception.response.status_code, exception)

  __main__.ApiHttpException: (500, HTTPError('500 Server Error: Internal
    Server Error for url: https://www.velib-metropole.fr/....